export const TELEGRAM_REPLY = {
  linked: "Telegram is linked to Sivraj. Send or forward a message here and your Twin will remember it.",
  needsLink: "Open Sivraj settings to link this Telegram account before I capture memory.",
  accountNeedsLink: "This Telegram account is not linked to a Sivraj Twin. Sign in to the wallet or user you want in Sivraj, then connect Telegram from Settings.",
  ambiguousLink: "This Telegram account is linked to more than one Twin. Open Sivraj settings and reconnect Telegram so I know exactly which Twin to use.",
  help: [
    "Sivraj Telegram commands:",
    "/start - start Sivraj or finish linking Telegram",
    "/status - show which Twin this Telegram account is linked to",
    "/whoami - same as /status",
    "/ask <question> - ask your Twin from memory or documents",
    "/remember <note> - save a memory explicitly",
    "/unlink - disconnect this Telegram account",
    "/switch - how to move this Telegram account to another Sivraj account",
  ].join("\n"),
  captured: "Captured. I'll process this into memory shortly.",
  duplicate: "Already captured.",
  revoked: "Telegram is disconnected from Sivraj. I will not capture messages here until you link again.",
  switchAccount: "To switch Sivraj accounts, sign in to the target wallet or user in Sivraj, open Integrations, and connect Telegram again. I will move this Telegram account to that Twin and disconnect the old active link.",
  mediaDeferred: "I saved the Telegram reference. Full media ingestion is coming next.",
  askUsage: "Ask your Twin with /ask followed by a question.",
  askThinking: "Checking your Sivraj context...",
  askProviderMissing: "Sivraj chat is not configured yet. Connect a chat model in Sivraj, then try /ask again.",
  askFailed: "I could not answer from Sivraj context right now. Try again in a moment.",
  rateLimited: "I am getting messages too quickly here. Give me a moment, then try again.",
  unsupported: "I can capture text today. Voice notes, photos, and files are next.",
  failed: "I received this, but capture failed. Try again in a moment.",
  expiredLink: "That link expired. Create a fresh Telegram link in Sivraj settings.",
} as const;
