export const TELEGRAM_REPLY = {
  linked: "Telegram is linked to Sivraj. Send or forward notes, links, screenshots, PDFs, and files here. Ask your Twin with /ask.",
  needsLink: "Open Sivraj settings to link this Telegram account before I capture memory.",
  accountNeedsLink: "This Telegram account is not linked to a Sivraj Twin. Sign in to the wallet or user you want in Sivraj, then connect Telegram from Settings.",
  ambiguousLink: "This Telegram account is linked to more than one Twin. Open Sivraj settings and reconnect Telegram so I know exactly which Twin to use.",
  help: [
    "Sivraj lives here as your memory dropbox and Twin.",
    "",
    "Drop anything useful:",
    "notes, links, screenshots, PDFs, docs, CSVs, Markdown, and text files.",
    "",
    "Commands:",
    "/ask <question> - ask from memory and documents",
    "/remember <note> - save something explicitly",
    "/status - show the linked Twin",
    "/whoami - same as /status",
    "/switch - move Telegram to another Sivraj account",
    "/unlink - disconnect Telegram",
  ].join("\n"),
  captured: "Captured. I'll process this into memory shortly.",
  duplicate: "Already captured.",
  revoked: "Telegram is disconnected from Sivraj. I will not capture messages here until you link again.",
  switchAccount: "To switch Sivraj accounts, sign in to the target wallet or user in Sivraj, open Integrations, and connect Telegram again. I will move this Telegram account to that Twin and disconnect the old active link.",
  mediaDeferred: "I saved the Telegram reference. Full media ingestion is coming next.",
  voiceDeferred: "I saved the voice note reference. Voice ingestion is coming next.",
  unsupportedMedia: "I saved the Telegram reference, but this file type is not supported yet.",
  mediaTooLarge: "That file is too large for Telegram memory capture right now.",
  mediaDownloadFailed: "I could not download that Telegram file. Please try sending it again.",
  capturedLink: "Captured link. I'll read and process it shortly.",
  capturedMedia: "Captured file. I'll process it into your Twin shortly.",
  askUsage: "Ask your Twin with /ask followed by a question.",
  askThinking: "Checking your Sivraj context...",
  askProviderMissing: "Sivraj chat is not configured yet. Connect a chat model in Sivraj, then try /ask again.",
  askFailed: "I could not answer from Sivraj context right now. Try again in a moment.",
  rateLimited: "I am getting messages too quickly here. Give me a moment, then try again.",
  unsupported: "Send notes, links, screenshots, PDFs, docs, CSVs, Markdown, or text files. Voice is coming next.",
  failed: "I received this, but capture failed. Try again in a moment.",
  expiredLink: "That link expired. Create a fresh Telegram link in Sivraj settings.",
} as const;
